---
appveyor.yml:
  delete: true
  unmanaged: false
.gitlab-ci.yml:
  delete: true
  unmanaged: false
.travis.yml:
  delete: true
  unmanaged: false

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
  hiera_config: spec/fixtures/hiera.yaml
