---
appveyor.yml:
  delete: true
  unmanaged: true
.gitlab-ci.yml:
  delete: true
  unmanaged: true
.travis.yml:
  delete: true
  unmanaged: true

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
  hiera_config: spec/fixtures/hiera.yaml
